Repackaging the OpenPAYGO-Token as a python module
EnAccess/OpenPAYGO pull request #10
Opened 2020-12-02 15:31 UTC by wan5xp

This can be repackaged into a python module for easy inclusion in other project

2020-12-16 18:04 UTC, alexpirine requested changes
Hey, I'm sorry but you reformated everything, so I cannot see the changes.

Could you please submit only changes relevant to your feature?

And open another PR to fix the formatting issue? (however I'm not sure @benmod will accept, many projects have different style guidelines, Django for instance [accepts up to 119 characters per line](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#python-style))

2020-12-16 18:04 UTC, syenchuk commented on .gitignore
> +venv.bak/
Please add a new line at the end of the file

P.S. Personal opinion. I am not a maintainer, just using the library.

2020-12-16 18:04 UTC, syenchuk commented on openpaygo/decode_token.py
> +            token)  # We get the base of the token
The source code doesn't enforce a 80 characters limit… maybe this is not necessary.

2022-09-05 08:54 UTC, benmod commented
Hi all! Thanks a lot for your work. Sadly I do not have the ability to approve PRs on this repo anymore but I integrated some of your changes into [our Fork](https://github.com/openpaygo/OpenPAYGO-Token) and published it on PyPi here: https://pypi.org/project/openpaygo-token/

You can just do ```pip install openpaygo-token``` to install it.

2022-09-06 10:50 UTC, BarnierVi commented
Hi @benmod, sorry there was a problem, now fixed. You shall now be able to approve PRs.

2022-10-05 06:27 UTC, Shawnmich7700 commented
Please which hardware and version is suitable for the Openpaygo Integration...I have the Arduino UNO R3, is it suitable or is there another board smaller than this for the integration? A picture of the setup will be appreciated.

2022-10-11 07:25 UTC, wan5xp commented
There is example implementation for Arduino shown here
https://github.com/EnAccess/OpenPAYGO-HW

Shawnmich7700 ***@***.***> schrieb am Mi. 5. Okt. 2022 um
08:27:

> Please which hardware and version is suitable for the Openpaygo
> Integration...I have the Arduino UNO R3, is it suitable or is there another
> board smaller than this for the integration? A picture of the setup will be
> appreciated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EnAccess/OpenPAYGO-Token/pull/10#issuecomment-1267999289>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABSSBCJ2U4NRWXHROUSGI7LWBUNVTANCNFSM4UKU2UWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 07:31 UTC, Shawnmich7700 commented
Thanks for your response...i will proceed with it and revert back to you.
In addition, how can I register on the application or how can I generate
tokens for my customers after programming weekly, and monthly subscriptions?

On Tue, Oct 11, 2022 at 8:26 AM Muhammad Ahmad ***@***.***>
wrote:

> There is example implementation for Arduino shown here
> https://github.com/EnAccess/OpenPAYGO-HW
>
> Shawnmich7700 ***@***.***> schrieb am Mi. 5. Okt. 2022 um
> 08:27:
>
> > Please which hardware and version is suitable for the Openpaygo
> > Integration...I have the Arduino UNO R3, is it suitable or is there
> another
> > board smaller than this for the integration? A picture of the setup will
> be
> > appreciated.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/EnAccess/OpenPAYGO-Token/pull/10#issuecomment-1267999289
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ABSSBCJ2U4NRWXHROUSGI7LWBUNVTANCNFSM4UKU2UWA
> >
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EnAccess/OpenPAYGO-Token/pull/10#issuecomment-1274210091>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3NVGNHWE3MSRO4P266MIFDWCUJA3ANCNFSM4UKU2UWA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-02-22 15:26 UTC, dmohns commented
Resolved via https://github.com/EnAccess/OpenPAYGO-Token/pull/18

2023-02-22 15:26 UTC, closed without merging